### PR TITLE
Library to mbed (only led)

### PR DESCRIPTION
**Pull request by StanWillems**

### CODE REVIEW

**Comment by StanWillems** [comment]
You can use
PCA9685 LedController1(64);   where LedController1 is a name to choose and 64 is the i2c adres in decimal
LedController1.init(1500);   where LedController1 is the same name and 1500 is the pwm frequency
LedController1.setPinPulseRange(15, 100); where LedController1 is the same name, 15 the led number [0-15] and 100 the duty cycle [0-100]

**Comment by alankrantas** [comment]
Why do you want to add a mbed driver in a MakeCode TypeScript extension library?

**Comment by jdarling** [comment]
I'm with @alankrantas on this, what is the point of adding mbed?

**Comment by StanWillems** [comment]
Hi,
I wanted to add it to your project because I have used your library to make
it.

Kind regards,
Stan Willems

**Comment by alankrantas** [comment]
Sorry for the late reply. The pxt- prefix means this is a repository designed to provide a library for micro:bit's MakeCode editor. Adding a different driver in it doesn't make sense. Also, this repository has been actively used by accessory makers, so we are not intend to change it unless it's necessary.

In fact, you can create your own mbed driver repository and make a PR to [Awesome micro:bit](https://github.com/carlosperate/awesome-microbit) to have your link listed. It would sure helping someone else who wants to code in C++ on micro:bits.

**Pull request closed without merging**
